### PR TITLE
fix: add blank spaces before join statements

### LINKED ISSUE #1: QueryBuilder doesn't add blank space before join statements
`
var query = new PlainSqlBuilder()
                .select("a.id as accountId, a.name as accountName, u.name as userName, u.email")
                .from("account a")
                .innerJoin("users u on a.user_id = u.id");`
The outcome of above query should be 
`
select a.id as accountId,
           a.name as accountName,
           u.name as userName, u.email 
from account a 
         inner join users u on a.user_id = u.id
`
but instead of that query builder returns the below
`
select a.id as accountId,
           a.name as accountName,
           u.name as userName, u.email 
from account ainner join users u on a.user_id = u.id
`

### PR DESCRIPTION
**Pull request by mrtyldr**

### CODE REVIEW

File: simple-query-builder-core/src/main/java/io/github/hbaykuslar/core/Spec.java [hunk 1]
```diff
@@ -11,17 +11,17 @@ public class Spec {
 
 
     public Spec join(String joinStatement) {
-        joins.add(joinStatement.trim());
+        joins.add(" join " + joinStatement.trim());
```
Comment (hbaykuslar) [inline simple-query-builder-core/src/main/java/io/github/hbaykuslar/core/Spec.java]: Your changes are legit solutions for the bug, but I prefer to keep SQL elements in lists without preceding or leading spaces and add necessary space characters in the "BaseQueryBuilder.buildSql" method. What do you think about this?
